# This is a basic workflow to help you get started with Actions

name: python-webapp

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Python lint
      - name: "Linting Python code"
        run: pylint webapp test_webapp.py
      
      # Run pytest
      - name: Run test suite
        run: pytest -v test_webapp.py
        
      # Create python distro
      - name: Create distro
        run: python3 setup.py bdist_wheel
      
      # Copies the package to target server
      - name: Copy the package to target server
        run: |
          cp dist/*.whl /Users/allan/CodeChallenge/DeployTarget/

      - name: Install package
        run: |
          cd /Users/allan/CodeChallenge/DeployTarget/
          python3 -m venv env1
          . env1/bin/activate
          pip install webapp-1.0.0-py3-none-any.whl
